### ISSUE TITLE
PDF地址打不开了捏

### ISSUE THREAD

**Issue by Tinnci** [zhcosin/elementary-math#21]
能不能修复一下a

**Comment by ghost** [comment]
可以查看 https://gitee.com/zhcosin/math-notes-publish/raw/master/elementary-math-note.pdf

**Comment by zhcosin** [comment]
> 可以查看 https://gitee.com/zhcosin/math-notes-publish/raw/master/elementary-math-note.pdf

这个链接有时候好像要登录才能打开，如果不能访问，可以邮件联系我 zhcosin@163.com，我发最新 pdf 文件.
